cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
 
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove, name='cart_remove'),

]
#handler404='cart.views.error_404_view'

products/urls.py
from django.urls import path
from . import views
#from .views import product_list,  product_detail, cart_list,index, add_to_cart, error_404_view
from .models import *


app_name='product'

urlpatterns=[
	path('products/product_list', views.product_list, name='product_list'),
	path('products/search_result/', views.search_result, name='search_result'),
	path('products/<id>/', views.product_detail, name='product_detail'),
	path('products/', views.index, name='index'),
]

handler404='products.views.error_404_view'

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views# reset password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('',include('cart.urls')),
    path('',include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="quantity")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404, render,redirect  
from .cart import Cart
from .forms import CartAddProductForm
from products.models import Product,ProductAttribute



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    
    cart = Cart(request)
    products = []
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        products.append(item)
    context = { 'cart': cart }
    context['products'] = products
    return render(request, 'cart/detail.html', context)

cart/templates/cart/cart_summary.html
cart summary page

cart/templates/cart/detail.html
 <h1>Your shopping cart</h1>
  <table class="table">
  
    <tbody>

      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td> 
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url  'cart:cart_remove' product.id %}">Remove</a></td>
            <td class="num">{{ item.price }}</td>
            <td class="num">{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        
        <td class="num">euro:{{ cart.get_total_price }}</td>

      </tr>

    </tbody>
  </table>


  <p class="text-right">
    <a href="{% url 'product:product_list'%}" class="button light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>

<br/>

You have added {{cart.get_total_qty}} products to cart in total