cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
 
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove, name='cart_remove'),

]
#handler404='cart.views.error_404_view'

products/urls.py
from django.urls import path
from . import views
#from .views import product_list,  product_detail, cart_list,index, add_to_cart, error_404_view
from .models import *


app_name='product'

urlpatterns=[
	path('products/product_list', views.product_list, name='product_list'),
	path('products/search_result/', views.search_result, name='search_result'),
	path('products/<id>/', views.product_detail, name='product_detail'),
	path('products/', views.index, name='index'),
]

handler404='products.views.error_404_view'

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views# reset password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('',include('cart.urls')),
    path('',include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.utils import timezone


# food size

class Size(models.Model):
    name=models.CharField(max_length=50)

    class Meta:
    	verbose_name='Size'
    	verbose_name_plural='Sizes'

    def __str__(self):
        return self.name

#food base

class Base(models.Model):
    name=models.CharField(max_length=50)

    class Meta:
    	verbose_name='Base'
    	verbose_name_plural='Bases'
    def __str__(self):
        return self.name


#food sauce

class Sauce(models.Model):
    name=models.CharField(max_length=50)

    class Meta:
    	verbose_name='Sauce'
    	verbose_name_plural='Sauces'
    def __str__(self):
        return self.name



class Category(models.Model):
	name=models.CharField(max_length=100)

	def __str__(self):

		return self.name

	class Meta:
		#verbose_name = "Category"
		verbose_name_plural='Categories'



# Product
class Product(models.Model):
	
	name = models.CharField(max_length=50, verbose_name="name")
	category=models.ForeignKey(Category, related_name='products',verbose_name="Category", on_delete=models.CASCADE, null=True)
	slug = models.SlugField(blank=True)
	description = models.TextField(blank=True,  verbose_name="description")
	featured = models.BooleanField(default=False, verbose_name="featured")
	created = models.DateTimeField(auto_now_add=True, verbose_name="created")
	updated = models.DateTimeField(auto_now_add=True, verbose_name="updated")
	available=models.BooleanField(default=True, verbose_name="available")
	has_attributes = models.BooleanField(default=False, verbose_name="attribute")
	image = models.ImageField(upload_to='images', null=True, blank=True, verbose_name="image")
	price=models.DecimalField(max_digits=4, decimal_places=2, default=9.99, verbose_name="price")



	class Meta:
		verbose_name = "Product"
		verbose_name_plural='Products'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
  		return reverse('product:product_detail', args=[str(self.id)])

	def image_tag(self):
		return mark_safe('<img src="%s" width="50" height="50" />)'% (self.image.url))


class ProductAttribute(models.Model):
    
    product = models.ForeignKey('Product', related_name="product_attrs", on_delete=models.CASCADE)
    size = models.ForeignKey('Size', related_name="size", on_delete=models.CASCADE)
    base = models.ForeignKey('Base', related_name="base", on_delete=models.CASCADE)
    sauce = models.ForeignKey('Sauce', related_name="sauce", on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(max_length=6, verbose_name="code", default="piz002")
    price=models.DecimalField(max_digits=4, decimal_places=2, default=9.99, verbose_name="price")
    
    class Meta:
    	verbose_name='ProductAttribute'
    	verbose_name_plural='ProductAttributes'


    def __str__(self):
        return self.product.name

products/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1","password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

products/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.http import JsonResponse
from django.db import models
from cart.views import *
from cart.forms import CartAddProductForm
from django.conf import settings

from .models import Category, Product,ProductAttribute
from django.contrib.auth.decorators import login_required

from django.db.models import Max,Min,Count,Avg

from django.shortcuts import get_object_or_404,redirect
from django.views.generic.list import ListView

from .forms import NewUserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from django.contrib import messages

from itertools import chain
from django.db.models import Q

#import django_filters



# def index(request):

#     return render(request,'products/index.html')


def index(request):

	cart = request.session.get(settings.CART_SESSION_ID, None)
	
	if cart:
		cart = sum(item['quantity'] for item in cart.values())
		context = {
			"data":cart
		}
		#print(cart)
		return render(request,'products/index.html',context)
	else:
		#print(cart)
		return render(request,'products/index.html')






# def product_list(request):

# 	products=Product.objects.order_by('id')[:10]
# 	categories=Category.objects.all()
# 	min_price=ProductAttribute.objects.aggregate(Min('price'))


# 	return render(request, 'products/product_list.html',  {'products':products,'categories':categories,'min_price':min_price})



def product_list(request):

	products=Product.objects.order_by('id')[:10]
	categories=Category.objects.all()
	min_price=ProductAttribute.objects.aggregate(Min('price'))
	cart = request.session.get(settings.CART_SESSION_ID,None)
	if cart:
		cart = sum(item['quantity'] for item in cart.values())
	return render(request, 'products/product_list.html', {'data':cart,'products':products,'categories':categories,'min_price':min_price})



#product detail 


def product_detail(request, id):

	try:
		product = get_object_or_404(Product, id=id)
		
		sizes=ProductAttribute.objects.filter(product=product).values('size__id','size__name').distinct()
		bases=ProductAttribute.objects.filter(product=product).values('base_id','base__name','price','size__id').distinct()
		sauces=ProductAttribute.objects.filter(product=product).values('sauce_id','sauce__name').distinct()
		category=Category.objects.get(id=id)
		cart_product_form = CartAddProductForm()

		context = {
	        'product': product,
	        'category':category,
	        'sizes':sizes,
	        'bases':bases,
	        'sauces':sauces,
			'cart_product_form': cart_product_form,
	        }
	
	except Product.DoesNotExist:
		
		raise Http404 ("this product id does not exit")
	return render(request, 'products/product_detail.html', context)


def search_result(request):

	q=request.GET['q']
	if not q:
		return HttpResponse("please input some texts")
	else:
		product_result=Product.objects.filter( Q(name__icontains=q)|Q(code__icontains=q)).order_by('name', 'price') #filter product results by search word
		category_result=Category.objects.filter(name__icontains=q).order_by('name') #filter category results by search word

		data = chain(product_result, category_result) #from itertools import chain
		return render(request,'products/search_result.html',{'data':data})



def error_404_view(request, exception):
	return render(request, 'products/404.html')

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'products/static/css/custom.css'%}">
      

      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <script src="{% static 'products/static/js/main.js'%}" defer></script>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark  bg-darker">
         <div class="container">
            <a class="navbar-brand" href="/">Nomiya</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                     <a class="nav-link text-white" href="/products/">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-white" href="product_list">Product List</a>
                  </li>
                 
                  <li class="nav-item">
                     <a class="nav-link text-white" href="/cart"><i class="fa fa-shopping-cart"></i> Cart (<span class="cart-list">{{data}}</span>)</a>

                  </li>
                  <form class="form-inline my-2 my-lg-0" action="{% url 'product:search_result' %}" >
                     {% csrf_token %}
                     <div class="input-group">
                        <input name="q" type="text" class="form-control" placeholder="search" />
                        <div class="input-group-append">
                           <button class="btn btn-dark" type="submit" id="button-addon2"><i class="fa fa-search" aria-hidden="true"></i></button>
                        </div>
                     </div>
                  </form>

                  
                  <li class="nav-item">

               
                     {% if user.is_authenticated %}
                     
                     <a data-fancybox data-type="iframe" class="nav-link text-white"  href="/logout"  data-iframe='{"preload":false}' role="button"  aria-haspopup="true" aria-expanded="false">  
                   
                     {% else %}
                      <a data-fancybox data-type="iframe" class="nav-link text-white"  href="/login"  data-iframe='{"preload":false}' role="button"  aria-haspopup="true" aria-expanded="false">
                     {% endif %}
                           <i class="fa fa-user "></i> 
                              </a>
                            
                  </li>
                  
                   <li class="nav-item">
                     <a class="nav-link text-white" href="/admin/">Admin</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>

      <section class="bg-darker bg-size-cover bg-position-center py-5 py-lg-10" style="background-image: url(/media/images/hero-bg.jpg);">
         <div class="container pb-5">
            <div class="row justify-content-center pb-5">
               <div class="col-xl-6 col-lg-7 col-md-8 col-sm-10 text-center">
                  <h5 class="text-light fw-light">#1 Food Delivery Service since 2010</h5>
                  <div class="h1 text-light mb-3 pb-4">
                     We deliver your favorite food fresh &amp; fast in
                     <div class="dropdown d-inline-block ms-1">
                        <a class="dropdown-toggle newcolor" href="#" data-bs-toggle="dropdown">New York</a>
                        <div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item fs-base" href="#">Los Angeles</a><a class="dropdown-item fs-base" href="#">Chicago</a><a class="dropdown-item fs-base" href="#">Houston</a><a class="dropdown-item fs-base" href="#">Philadelphia</a><a class="dropdown-item fs-base" href="#">San Diego</a><a class="dropdown-item fs-base" href="#">Miami</a></div>
                     </div>
                  </div>
                  <a class="btn btn-danger" href="#cuisine" data-scroll="">What do you want to eat?</a>
               </div>
            </div>
         </div>
      </section>
      {% block body %}
      {% block content %}
      {% endblock %}
      {% endblock %}
      {% block extra_body %}
      {% endblock %}
      <footer class="footer bg-darker pt-5">
         <div class="container pt-2">
            <div class="row pb-2">
               <div class="col-lg-2 col-sm-4 pb-2 mb-4">
                  <div class="mt-n1"><a class="d-inline-block align-middle" href="#"><img class="d-block mb-4" src="/media/images/logo.png" width="117" alt="Cartzilla"></a></div>
               </div>
               <div class="col-lg-2 col-sm-4">
                  <div class="widget widget-links widget-light pb-2 mb-4">
                     <h4 class="widget-title text-light">Join us</h4>
                     <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Careers</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Restaurants</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Become a Courier</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">About</a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-2 col-sm-4">
                  <div class="widget widget-links widget-light pb-2 mb-4">
                     <h4 class="widget-title text-light">Let us help you</h4>
                     <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link changecolor" href="#">Help Center</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Support</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Contacts</a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-2 col-sm-4">
                  <div class="widget widget-links widget-light pb-2 mb-4">
                     <h4 class="widget-title text-light">Follow us</h4>
                     <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Facebook</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Twitter</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Instagram</a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-lg-2 col-sm-4">
                  <div class="widget widget-links widget-light pb-2 mb-4">
                     <h4 class="widget-title text-light">Download App</h4>
                     <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Apple Store</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Google Play</a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <hr class="hr-light mt-md-2 mb-3">
            <div class="d-md-flex justify-content-between pt-4 pb-1">
               <div class="pb-4 fs-xs text-light opacity-50 text-center text-md-start">© All rights reserved. Made by <a class="text-light" href="https://createx.studio/" target="_blank" rel="noopener">Createx Studio</a></div>
               <div class="widget widget-links widget-light pb-4">
                  <ul class="widget-list d-flex flex-wrap justify-content-center justify-content-md-start">
                     <li class="widget-list-item ms-4"><a class="widget-list-link fs-ms" href="#">Privacy Policy</a></li>
                     <li class="widget-list-item ms-4"><a class="widget-list-link fs-ms" href="#">Terms &amp; Conditions</a></li>
                     <li class="widget-list-item ms-4"><a class="widget-list-link fs-ms" href="#">Cookies Policy</a></li>
                  </ul>
               </div>
            </div>
         </div>
      </footer>
      <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script src="jquery.fancybox.min.js"></script>
   </body>
</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
<section class="container py-4 my-lg-3 py-sm-5" id="cuisine">
   <h2 class="text-center pt-4 pt-sm-3">Trending food in your city</h2>
   <p class="text-muted text-center mb-5">Choose what you want and we dilever it to you</p>
   <div class="row">
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/04.jpg" alt="Pizza &amp; Pasta">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black";>Pizza &amp; Pasta</h3>
            </div>
         </a>
      </div>
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/01.jpg" alt="Burgers &amp; Fries">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black;">Burgers &amp; Fries</h3>
            </div>
         </a>
      </div>
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/02.jpg" alt="Noodles">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black";>Noodles</h3>
            </div>
         </a>
      </div>
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/03.jpg" alt="Sushi &amp; Rolls">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black";>Sushi &amp; Rolls</h3>
            </div>
         </a>
      </div>
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/05.jpg" alt="Coffee &amp; Desserts">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black";>Coffee &amp; Desserts</h3>
            </div>
         </a>
      </div>
      <div class="col-md-4 col-sm-6 mb-grid-gutter">
         <a class="card border-0 shadow"  href="product_list">
            <img class="card-img-top" src="https://cartzilla.createx.studio/img/food-delivery/category/06.jpg" alt="Healthy &amp; Food">
            <div class="card-body py-4 text-center">
               <h3 class="h5 mt-1" style="color:black";>Healthy &amp; Food</h3>
            </div>
         </a>
      </div>
   </div>
</section>
{% endblock %}

products/templates/products/product_detail.html
<!--to be done-->
{{ product.name }}<br/>
{{ product.category }}</br>
{% for size in sizes %}
   

   <button type="button" class="btn btn-secondary">{{size.size__name}}</button>


{% endfor %}
<br>

{% for base in bases %}
          
       <button type="button" class="btn btn-secondary">{{base.base__name}}</button><br>
{% endfor %}


<br>

<th>€<span class="product-price-{{product.id}}">{{product.price}}</span></th>


 {{ product.description|truncatewords:5 }}</br>
 <img src="{{product.image.url}}" alt ="image"/><br/>


    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>

products/templates/products/product_list.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}

<section class="container tab-content py-4 py-sm-5">
   <h2 class="text-center pt-2 pt-sm-0 mb-sm-5">Pizza</h2>
   <div class="row pt-3 pt-sm-0">
      {% for product in products %}
      <!-- Item-->
      <div class="col-lg-3 col-md-4 col-sm-6 mb-grid-gutter" style="margin-bottom:15px">
         <div class="card product-card border pb-2">
            <a class="d-block" href="#quick-view" data-bs-toggle="modal"><img class="card-img-top" src="{{product.image.url}}" alt="Pizza"></a>
            <div class="card-body pt-1 pb-2">
               <h3 class="product-title fs-md"><a style="color:black;font-size: 0.9375rem !important";href="#quick-view" data-bs-toggle="modal"> {{ product.name }}</a></h3>
               <p class="fs-ms text-muted" style="font-size: 0.9375rem !important">{{ product.description }}</p>
             
               <div class="d-flex align-items-center justify-content-between">
                   <div class="product-price"><span class="text-accent">€{{product.price}}</span></div>
               
                <button class="btn btn-danger btn-sm" type="submit"  onclick="location.href = '{{product.get_absolute_url}}'">+<i class="fa fa-shopping-cart"></i> </button>
               </div>

            </div>
         </div>
      </div>
      {% endfor %}
      <!-- Load more button-->
      <nav class="d-md-flex justify-content-between align-items-center text-center text-md-start pt-2 pb-4 mb-md-2" aria-label="Page navigation">
         <div class="d-md-flex align-items-center w-100">
            <span class="fs-sm text-muted me-md-3">Showing 8 of 24 items</span>
            <div class="progress w-100 my-3 mx-auto mx-md-0" style="max-width: 10rem; height: 4px;">
               <div class="progress-bar bg-dark" role="progressbar" style="width: 18%;" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
         </div>
         <button class="btn btn-outline-secondary" type="button">Load more items</button>
      </nav>
</section>
</div>
{% endblock %}

products/templates/products/search_result.html
{% for data in data %}
	{% if data.price %}
	Product:
{{data.name}}--{{data.price}}<br/>

   {% else %}
  Category-{{data.name}}<br/>
   {% endif %}
  

{% empty %}   
	
<p>hmm, embarrasing, we don't have such a product, perhaps try some other search word ....</p>

{% endfor %}	
	